{% set version = '1.1.12' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-longitudinal
  version: {{ version|replace("-", "_") }}

source:
  fn: longitudinal_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/longitudinal_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/longitudinal/longitudinal_{{ version }}.tar.gz
  sha256: d4f894c38373ba105b1bdc89e3e7c1b215838e2fb6b4470b9f23768b84e603b5

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1001
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-corpcor >=1.6.8
  run:
    - r-base
    - r-corpcor >=1.6.8

test:
  commands:
    - $R -e "library('longitudinal')"           # [not win]
    - "\"%R%\" -e \"library('longitudinal')\""  # [win]

about:
  home: http://strimmerlab.org/software/longitudinal/
  license: GPL (>= 3)
  summary: Contains general data structures and functions for longitudinal data with multiple
    variables, repeated measurements, and irregularly spaced time points. Also implements
    a shrinkage estimator of dynamical correlation and dynamical covariance.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
