travis:
  secure:
    BINSTAR_TOKEN: jrgtQ+DSvo2GyKIuHu2fB4EIlAfkpxLUE4A4SCYApbyIPJgIWtRdjx7H9wa6ieBLNJ1olqhKOmVx/tBqTv1v9vk4alM/3lo3ri+VfYiCLkHOyewLAPDconkDZrrSkyVjVoExp4yVOsTEJrDZRDmFfeT+73WwZVA7ucp/TEZDNCLj0Zy5ipCuMObPiQAtpEzgDRM4HU483/Lp+cl4OPTFzkfZb/Bwhe7GdhbiFWmYKhHPMO3RO34FaMQxycLSQ6wWUQrma4U90yFoam7R8Qusq5dDMtL75nszrAVCAtYcqIVJvuYM3NOe4bquMOUXqg26jX35daVTgMNBnd6ZOLC3oV3irzy8WRePuk/hvoouWkA0UygOYJLqwEvQM7HFuaVF2QdS1sYsZLp+yXLu/4P2Ln9EX3iEEVBd77ZE+VFkXP4eL/KN/napDW2FXtSIDeH0SQxF7kyVdHkHfOxScDGDcVKNpcidvELvKvqPwE85FwUgZ2pWnr+kWbjOFlNOJZQjjVM++5duZo5AfhcoB1opfApm6xyAuHiBVkCm48HVcmI8MF2/ydqFGYlzeQz/bE8olJePNm5z7KfG9efjJEDNxFLZYUiGZ2vgA3z0p/a32yeBGkTHpbS/jsPIQUU0M1I5LC8KP/GeCvwzuC2sW2eXe5c5xulLGL5oUJIKl5posIg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
