travis:
  secure:
    BINSTAR_TOKEN: LIEcKY/ljCMDvMVEFj+XIP42xp6bYbDQ1JjhpZDd1dYmi3+/wjNfCfE2iTLJd5xwb/E65znNseMhWdUz+m8rS/jWayHKGGKX98Cawbgphr12NKvJawNjUmpMkkSTjLq9SIAQVdC7fiqn8aJWplgqfPt0YHpkXW6hDz+WD+eqiPIwFshTiFb0ORI6zHrN1I1wiMGdotKKQWgANwdGyK7qltyLibxztwOMBpjehMfGCxi82bEHrkBIGcyfjLjNAeWptpf7pKw73uiyslo2EHKawalwQ9M2nmtInChXqR7ZZ4qtHECgol8hBw8oOrOJFguKqVg1IlD6OA1Vt8YRE8RLfD7Cx7KLB4bZaX+3ha8htdQt43VPu+oA0wvzyqHMygUqsbsFa5Hb0Zar7DhmAdAzsgjByOt9F6zflI39JpQHSBaFg8t0j27f+1r5jve5Z+RXs3fCeI8MgIQ+SlYMGUxwZpbZlNcVyT23atXox9xJL7gZiLLQaGQc+swLVfqA6OXYAdB6hAu7VLoL7X+YT6Ls7S6zz5Q0mFm33LadhV11XQJYQ4XSfoi1NZ0QpVvAAfhAnGe5za2L1mQVTMHtXFONRjnN8cN9woFMvx9tn3UkWUd6mvGOeTWiKbyvTwty1FFdRtLjGW9jdXBKydSRo7IqOCYiuFYqvjFn05SGyZZfRfo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
