travis:
  secure:
    BINSTAR_TOKEN: bcwlJIohsFXE/bxVZ+eF+w8RbzdIuJdOTvlhKdnFMdShPC6XlF+sDTj62U9x152c1VhSEL31zjpEF40PvOcgpbtlLtMrodmjCxX32gOLzZNG+JpneyY8OiYTGFCXEzJtxqX73tGN8cChpsrpF6KZr9ghoJ1ohZjE5cOeexdgyCaSWuiz2AnfjHHLbgEuPn/OCfbk/6T/u/DdjVYqMh+13ElpndGSOEoznp+1NSl+dhELVpK4V35LmJguTbjphwZadFW7wBDTnzCy8gBBiUxhhJ7Bx9NOoc6zmTbzZGnWARyx8MRDYTd8UiqQZ1t+0IVE5tYUPHQSwkzq0zTWZN4iR+T1Z5rflJDCNsXAMfdqbtKwROSloCfUSLuUy24coE+IB7P4JmDuzhGIR8CVwW0MYilMfh6LlbB+QOxjxmcZRAwQSnFF8h01LHSCNiJq0RkSN7iUDYC+u9OpNar71iucp1P2Z3SjENGEZjJK/z+hs57XifVotXbBnW6T5Cv+JOMhcHdLImJWYYnJwNfq7gC5cA7m3i+OwNlvCDXEmBSxiVIGHimSRT6+hX7rPdf5zC7XuCFaQHguax5Mrm8Rxt4F09zMTJV4ir/SvyWPT8DJjK/fzmrqV8NFeCnQjX74zsV8AqCttdEXNHLfFd970sqhkH3KX2tU5jbtJ68nRXZ4f3c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
