travis:
  secure:
    BINSTAR_TOKEN: Kbmv1N+k6E7+oGBY1JEJtBh66sLUPW17nfcneqggoExka9xjiXTBZS8pP8u54R/jZXTi+p6f9khedIUFegDfdhomd3/+Fue+GdEAsBEmyaXet3sjSTVBTCNnjpWTcZacSbnDtbjiSqve3XxpUMS39xkMxGkdgl1j3W/M42vLU0M6WZ4M6tdsiJjHSeTrKUTltfm6wz10Ac7Zdtf9nY/8iXiPwzxPLTbAc7za+i8BtPW1uIaVzep6ck3GzKlzN5kAVuFI1KRMsFpeBK01iV3GEgP2d7X7K3WF/UpxFMUCeFOtcy/DukVa88Nd3mF2xOlDQDCPYSHOlgZyuPWvhZFVxLE0GCsfNFuIrSXuMfrocIM2W6OZyiol1fEyKzHTK3oUh6Glt8ZykLNb8JkB/nAv9zizWLn/lrbs5owRZJgw9gTKb5UYkK7H8utNbcgSN7rcugqYxdgbxQdsYL1r0qjSKQaj0NCcCOXdNpDguLOp5+eBKQyYJAfueB6JpWCdfRjgxVmB7XHGzMIzW+/iAv/Fzp+ZSDe/gWck5MEkk3EywZIlptOq0ZCRp838QK4//aG/Ai765Oe3A1swuwfKLbAERVydnRWtYhf5y8h/E05A8Bo6gERSFh6OCQrKbcUg/IMM1uxPq6d497DQyCBSqcFWRz45WFsXO7uQSawp4HDNa/o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
