travis:
  secure:
    BINSTAR_TOKEN: fRS3C8GkeABKsjGFi/3Qeo3pQ5R/RPVtLJB73Yxh32OSP9uTM1nQ3UZgKt2TwpKJo7TahiFlLq0dt0yKFCQXRdRebsgtK8/W/goQ/OIQSItjIBoLGBjrywP0v8nbXNB6374jHnlqrwnz862XE79yCP0OfrCsMKILxVqVJnX+13o7PsS8hGjrQok0uQFZe5KWfLg7/FJ7MgpTIllPQtphqwFP9h669FGKa8F1N7WQPLmqTTTBck/tAl9/EQVUhoYkjNk8ZFrCen6vQhm2rlHSwqvVDTzcwhz5re+injIVrhEaDTdx87WY6FBGSqD8fHEmhgr59cr+FcCMCwmYDcc4YFujwTh/lp4qvlp0v3TUAeW/x2Zo1Y/c/EnypYREoLiBbiu/rGjmlrrt9SrgN817fuhhUNKRMu3ymBl3I7+zqbuecmpvu4/JrzS8CYlVbjLnAbjLW5gOBlY46dP3LGPgJ9x6KD8r0IMBgd6DNMxRbWGuNYK91joqTJAAKLYIGlzPBqPLSUV8bDIHPy3iyr1xhlaF3T1OqKCqVI3H/QHlcGweh9+V/8dBjueRTj3j9OxxRiUy0WOxIdsBy+ptGzQO06WBnbEDy+p1fiSqCoNzmLcCyaftC1h0ssIU2qHQkjOaEtAeY5JbXdYlBNWguFiqeABfuhC4wcdvs87YNQMtguM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
